<template>
  <div id="app-container" :class="{ 'dark-mode': isDarkMode }">
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>

<script setup lang="ts">
useSeoMeta({
  title: "Nerdy Novel",
  ogTitle: "Nerdy Novel",
  description:
    "Nerd Novel is a quirky and humorous website where all the novels are uniquely generated by AI.",
  ogDescription:
    "Nerd Novel delivers a one-of-a-kind reading experience filled with wacky and offbeat adventures.",
  ogImage: "https://example.com/image.png",
  twitterCard: "summary_large_image"
})
const { isDarkMode } = useDarkMode()
</script>

<style>
:root {
  --background-color-light: #f4f4f4;
  --background-color-dark: #121212;
  --text-color-light: #333;
  --text-color-dark: #f4f4f4;
  --novel-background-color-dark: #1e1e1e;
  --novel-background-color-light: #fff;
  --primary-button-color: #ff6f61;
  --header-bg-light: linear-gradient(135deg, #6e45e2, #88d3ce);
  --header-bg-dark: linear-gradient(135deg, #4a3c9e, #6b9c8c);
  --footer-bg-light: #d3d3d3;
  --footer-bg-dark: #333;
}

body {
  font-family: 'ZCOOL KuHei', sans-serif;
  margin: 0;
  padding: 0;
  background-color: var(--background-color-light);
  color: var(--text-color-light);
  transition: background-color 0.3s, color 0.3s;
}

#app-container.dark-mode {
  background-color: var(--background-color-dark);
  color: var(--text-color-dark);
}
</style>
