<template>
  <div>
    <NuxtLayout>
      <NuxtPage />
    </NuxtLayout>
  </div>
</template>

<script setup lang="ts">
useSeoMeta({
  title: "Nerdy Novel",
  ogTitle: "Nerdy Novel",
  description:
    "Nerd Novel is a quirky and humorous website where all the novels are uniquely generated by AI.",
  ogDescription:
    "Nerd Novel delivers a one-of-a-kind reading experience filled with wacky and offbeat adventures.",
  ogImage: "https://example.com/image.png",
  twitterCard: "summary_large_image"
})
</script>
