version: '3.9'
services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    ports:
      - "3000:3000"
